// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQoX-_GwJXdWxceCDX7945U8MPNk87hsI',
    appId: '1:175384416117:android:3f4028d3f9c19c641d8d3c',
    messagingSenderId: '175384416117',
    projectId: 'beta-8009a',
    storageBucket: 'beta-8009a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkTQRdZTdTKPp1gvLqMaxSkbCspLU4ySs',
    appId: '1:175384416117:ios:5fff333773519c0b1d8d3c',
    messagingSenderId: '175384416117',
    projectId: 'beta-8009a',
    storageBucket: 'beta-8009a.appspot.com',
    androidClientId: '175384416117-la4b2j0q0ht2fott8e8qt26pd9akrv2h.apps.googleusercontent.com',
    iosClientId: '175384416117-1qqel01973jqbup3poej9ukjbnpf0a7c.apps.googleusercontent.com',
    iosBundleId: 'com.example.betaVersion',
  );
}
